name: mybranch_Test_build

on:
  push:
    branches:
      - mybranch

jobs:
  test:
    name: Test on ${{ matrix.os }} and Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 18
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Nothing
        run: echo "Nothing to do here"